apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: btcusdt-producer
  labels:
    app.kubernetes.io/name: btcusdt-producer
    app.kubernetes.io/part-of: kafka
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: btcusdt-producer
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
